server:
  port: 8888

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/puhaiyang/spring-boot-cloud
          search-paths: config-repo
  rabbitmq:
    host: ${RABBITMQ_SERVER_HOST:rabbitmq}
    port: ${RABBITMQ_SERVER_PORT:30672}
    username: ${RABBITMQ_SERVER_USERNAME:user}
    password: ${RABBITMQ_SERVER_PASSWORD:bitnami}

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
